services:
  backend:
    build: ./backend
    container_name: grid-backend
    ports:
      - "8001:8001"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: grid-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always